<?php

use App\ProductType;

return [
    [
        'type_id' => 2,
        'image' => 'Frontstage/images/product1.png',
        'features' => "可以該產品的特色應用,
                        預設五排文字可以寫,
                        每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。,
                        內容由管理者設定。",
        'remark' => "預設兩排文字輸入，每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。",
        'introduction' => '該類別簡易介紹，簡單二十個字數內即可，讓瀏覽者更加了解該分類內容產品...',
        'chart_image' => 'Frontstage/images/product-detail1.jpg',
        'video_url1' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url2' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url3' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url4' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'pdf' => 'Frontstage/images/product-detail1.jpg',
        'acting' => 'NIKKI DENSO',
        'name' => 'SQ-450A',
    ],
    [
        'type_id' => 2,
        'image' => 'Frontstage/images/product6.png',
        'features' => "可以該產品的特色應用,
                        預設五排文字可以寫,
                        每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。,
                        內容由管理者設定。",
        'remark' => "預設兩排文字輸入，每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。",
        'introduction' => '該類別簡易介紹，簡單二十個字數內即可，讓瀏覽者更加了解該分類內容產品...',
        'chart_image' => 'Frontstage/images/product-detail1.jpg',
        'video_url1' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url2' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url3' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url4' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'pdf' => 'Frontstage/images/product-detail1.jpg',
        'acting' => 'NIKKI DENSO',
        'name' => 'JDBN-65',
    ],
    [
        'type_id' => 2,
        'image' => 'Frontstage/images/product6-2.png',
        'features' => "可以該產品的特色應用,
                        預設五排文字可以寫,
                        每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。,
                        內容由管理者設定。",
        'remark' => "預設兩排文字輸入，每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。",
        'introduction' => '該類別簡易介紹，簡單二十個字數內即可，讓瀏覽者更加了解該分類內容產品...',
        'chart_image' => 'Frontstage/images/product-detail1.jpg',
        'video_url1' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url2' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url3' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url4' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'pdf' => 'Frontstage/images/product-detail1.jpg',
        'acting' => 'NIKKI DENSO',
        'name' => 'JDB-240',
    ],
    [
        'type_id' => 2,
        'image' => 'Frontstage/images/product6-3.png',
        'features' => "可以該產品的特色應用,
                        預設五排文字可以寫,
                        每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。,
                        內容由管理者設定。",
        'remark' => "預設兩排文字輸入，每排文字最多設定可以輸入三十個字數，可以連續輸入不斷行，無輸入就空白無資料。",
        'introduction' => '該類別簡易介紹，簡單二十個字數內即可，讓瀏覽者更加了解該分類內容產品...',
        'chart_image' => 'Frontstage/images/product-detail1.jpg',
        'video_url1' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url2' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url3' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'video_url4' => 'https://www.youtube.com/embed/C1IP05_Hk0Y?list=PLGyv6kOJhxI_FB7C3WLLjO2LUmIus4G88',
        'pdf' => 'Frontstage/images/product-detail1.jpg',
        'acting' => 'NIKKI DENSO',
        'name' => 'JDB-180',
    ],
];
